name:Github Actions Demo
run-name:${{ github.actior }} is running our GitHUb Actions
on:
 workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on:ubuntu-latest
    steps:
    - run:echo "The job was automatically Triggered by ${{ github.event_name}} event"
    - run:echo "This job is now running on a ${{ runner.os}} server hosted by GitHub"
    - run:echo "The naem of your branch is ${{ github.ref}} and your repository is ${{gitub.repository}}
    - name:Check out repository code
      uses: actions/checkout@v4
      run:echo "The ${{github.repository}} repository has been cloned to the runner
    - name:List files in the repository
      run: |
        ls ${{github.workspace}}
    - run:echo "This jobs status is ${{ job.status}}
