name: A workflow for my Hello World file
on: workflow_dispatch
jobs:
  build-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Check out code
      - name: Hello World
        run: echo "Hello World"
      - name: Index.html content
        run: |
          cat "Index.html"
          cat "Courses.html"
          echo "The main.yml workflow successfully executed"
  
